version: '3.8'
services:
  localdb:
    container_name: hana4db
    image: mysql:8.0
    ports:
      - 3307:3307
    environment:
      MYSQL_ROOT_PASSWORD: TestdbRoot
      MYSQL_DATABASE: testdb
    command:
      - --character-set-server=u
      - --collation-server=utf8mb4_unicode_ci
      - --log_bin_trust_function_creators=1
    volumes:
      - ./mysql:/var/lib/mysql
